version: '3'
volumes:
  mysql_8_0-data:

services:
  db:
    image: mysql:8.0
    container_name: rails_mysql
    hostname: db
    ports:
      - "33306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    volumes:
      - mysql_8_0-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails_web
    volumes:
      - .:/rails6_and_mysql
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - db
    command: bundle exec rails server -b 0.0.0.0
